repository: https://github.com/prastamaha/gitops
environment: prd

projects:
   - name: demo
     description: demo project

applications:
  - name: echo-server
    namespace: echo-server  # namespace will automatically created if not exists
    project: demo
    revision: HEAD
