apiVersion: v2
name: templates
description: A Helm chart for Kubernetes
type: application
version: 0.1.0

dependencies:
- name: echo-server
  version: 0.5.0
  repository: https://ealenn.github.io/charts
